#!/usr/bin/env node
import { existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { listFilesRecursive, readJson } from "./lib.mjs";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const required = [
  "README.md",
  "CODEX.md",
  "START-NEW-PROJECT.md",
  "USAGE-GUIDE.md",
  "frameworks/lifecycle.md",
  "frameworks/research-deep-methodology.md",
  "frameworks/build-plan-deep-methodology.md",
  "frameworks/rigor-modes.md",
  "frameworks/design-dna.md",
  "frameworks/frontend-visual-qa.md",
  "frameworks/quality-gate-matrix.md",
  "frameworks/narrative-validation.md",
  "frameworks/governance-and-evolution.md",
  "frameworks/learning-loop.md",
  "frameworks/competitive-benchmark.md",
  "frameworks/context-routing-and-help.md",
  "frameworks/agentic-opportunity-audit.md",
  "frameworks/intelligence-system-plan.md",
  "frameworks/intelligence-architecture-selection.md",
  "frameworks/agent-engineering-skill-stack.md",
  "frameworks/skill-factory.md",
  "frameworks/agent-os-runtime.md",
  "frameworks/agent-network-interop.md",
  "frameworks/agentic-zero-trust.md",
  "frameworks/capability-access-readiness.md",
  "frameworks/tool-surface-routing.md",
  "frameworks/quick-flow.md",
  "frameworks/vertical-slice-planning.md",
  "frameworks/context-distillation.md",
  "frameworks/test-architecture.md",
  "frameworks/project-context.md",
  "frameworks/session-close-and-context-save.md",
  "frameworks/expert-councils.md",
  "frameworks/skill-workflow-architecture.md",
  "schemas/project-state.schema.json",
  "schemas/project-classification.schema.json",
  "schemas/lesson.schema.json",
  "schemas/full-mode-coverage-catalog.schema.json",
  "schemas/agentic-system-patterns.schema.json",
  "schemas/intelligence-architecture-catalog.schema.json",
  "schemas/agent-engineering-catalog.schema.json",
  "schemas/agent-os-runtime-catalog.schema.json",
  "schemas/agent-network-interop-catalog.schema.json",
  "schemas/agentic-zero-trust-catalog.schema.json",
  "schemas/capability-access-catalog.schema.json",
  "schemas/tool-surface-routing-matrix.schema.json",
  "schemas/workflow-manifest.schema.json",
  "schemas/session-brief.schema.json",
  "schemas/session-record.schema.json",
  "catalogs/full-mode-coverage-catalog.json",
  "catalogs/agentic-system-patterns.json",
  "catalogs/intelligence-architecture-catalog.json",
  "catalogs/agent-engineering-catalog.json",
  "catalogs/agent-os-runtime-catalog.json",
  "catalogs/agent-network-interop-catalog.json",
  "catalogs/agentic-zero-trust-catalog.json",
  "catalogs/capability-access-catalog.json",
  "catalogs/tool-surface-routing-matrix.json",
  "catalogs/workflow-manifest.json",
  "workflows/README.md",
  "workflows/context-routing/step-01-load-state.md",
  "workflows/context-routing/step-02-compute-next-action.md",
  "workflows/context-routing/step-03-report-brief.md",
  "workflows/agentic-opportunity/step-01-audit.md",
  "workflows/agentic-opportunity/step-02-intelligence-system-plan.md",
  "workflows/agentic-opportunity/step-03-readiness-gate.md",
  "workflows/intelligence-architecture/step-01-substrate-selection.md",
  "workflows/intelligence-architecture/step-02-loop-architecture.md",
  "workflows/intelligence-architecture/step-03-readiness-gate.md",
  "workflows/agent-engineering/step-01-seven-skill-audit.md",
  "workflows/agent-engineering/step-02-skill-gap-map.md",
  "workflows/agent-engineering/step-03-skill-factory-readiness.md",
  "workflows/agent-os-runtime/step-01-kernel-map.md",
  "workflows/agent-os-runtime/step-02-runtime-contracts.md",
  "workflows/agent-os-runtime/step-03-readiness-gate.md",
  "workflows/agent-network-interop/step-01-network-map.md",
  "workflows/agent-network-interop/step-02-contracts-boundaries.md",
  "workflows/agent-network-interop/step-03-readiness-gate.md",
  "workflows/agentic-zero-trust/step-01-threat-model.md",
  "workflows/agentic-zero-trust/step-02-controls-contracts.md",
  "workflows/agentic-zero-trust/step-03-readiness-gate.md",
  "workflows/capability-access/step-01-inventory.md",
  "workflows/capability-access/step-02-map-surfaces.md",
  "workflows/capability-access/step-03-readiness-gate.md",
  "workflows/quick-flow/step-01-clarify.md",
  "workflows/quick-flow/step-02-write-quick-spec.md",
  "workflows/quick-flow/step-03-implement-slice.md",
  "workflows/quick-flow/step-04-verify.md",
  "workflows/quick-flow/step-05-learn.md",
  "workflows/full-mode-readiness/step-01-research-gate.md",
  "workflows/full-mode-readiness/step-02-build-plan-gate.md",
  "workflows/full-mode-readiness/step-03-execution-readiness.md",
  "workflows/session-close/step-01-gather.md",
  "workflows/session-close/step-02-save-record.md",
  "workflows/session-close/step-03-health-check.md",
  "templates/shared/project-state.template.json",
  "templates/shared/session-record.template.json",
  "templates/shared/agentic-opportunity-audit.template.md",
  "templates/shared/intelligence-system-plan.template.md",
  "templates/shared/intelligence-architecture-decision.template.md",
  "templates/shared/agent-engineering-audit.template.md",
  "templates/shared/agent-os-runtime-plan.template.md",
  "templates/shared/agent-network-interop-plan.template.md",
  "templates/shared/agentic-zero-trust-plan.template.md",
  "templates/shared/skill-inventory.template.md",
  "templates/shared/skill-spec.template.md",
  "templates/shared/capability-access-map.template.md",
  "templates/shared/project-codex.template.md",
  "templates/shared/project-context.template.md",
  "templates/shared/distillate.template.md",
  "templates/shared/memory/project-brief.template.md",
  "templates/shared/memory/product-context.template.md",
  "templates/shared/memory/system-patterns.template.md",
  "templates/shared/memory/tech-context.template.md",
  "templates/shared/memory/active-context.template.md",
  "templates/shared/memory/progress.template.md",
  "templates/light/quick-spec.template.md",
  "templates/full/master-build-plan.template.md",
  "templates/full/evidence-ledger.template.json",
  "templates/full/research-category.template.md",
  "templates/full/frontend-visual-qa.template.md",
  "templates/full/postmortem.template.md",
  "templates/full/mode-downgrade-record.template.md",
  "templates/full/test-strategy.template.md",
  "templates/full/traceability-matrix.template.md",
  "scripts/classify-project.mjs",
  "scripts/bootstrap-project.mjs",
  "scripts/validate-state.mjs",
  "scripts/capture-lesson.mjs",
  "scripts/next-action.mjs",
  "scripts/session-brief.mjs",
  "scripts/plan-agentic-system.mjs",
  "scripts/plan-intelligence-architecture.mjs",
  "scripts/plan-agent-skills.mjs",
  "scripts/plan-agent-os-runtime.mjs",
  "scripts/plan-agent-network.mjs",
  "scripts/plan-agentic-zero-trust.mjs",
  "scripts/plan-capabilities.mjs",
  "scripts/route-tool.mjs",
  "scripts/verify-plan.mjs",
  "scripts/distill-context.mjs",
  "scripts/context-utils.mjs",
  "scripts/save-context.mjs",
  "scripts/context-health.mjs",
  "agents/intelligence-architecture-reviewer.md",
  "agents/agent-engineering-reviewer.md",
  "agents/agent-os-runtime-reviewer.md",
  "agents/agent-network-interop-reviewer.md",
  "agents/agentic-zero-trust-reviewer.md"
];

const missing = required.filter((path) => !existsSync(join(root, path)));
const jsonFiles = listFilesRecursive(join(root, "schemas"))
  .concat(listFilesRecursive(join(root, "templates")).filter((p) => p.endsWith(".json")))
  .concat(listFilesRecursive(join(root, "catalogs")).filter((p) => p.endsWith(".json")));
const jsonErrors = [];

for (const file of jsonFiles) {
  try {
    readJson(file);
  } catch (error) {
    jsonErrors.push(`${file}: ${error.message}`);
  }
}

const ok = missing.length === 0 && jsonErrors.length === 0;
console.log(JSON.stringify({ ok, missing, jsonErrors }, null, 2));
process.exit(ok ? 0 : 1);
